services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Repository services
  Tourze\CommentBundle\Repository\:
    resource: '../../Repository/'

  # Service layer
  Tourze\CommentBundle\Service\:
    resource: '../../Service/'

  # Event listeners
  Tourze\CommentBundle\EventListener\:
    resource: '../../EventListener/'

  # Commands
  Tourze\CommentBundle\Command\:
    resource: '../../Command/'
